CREATE TABLE vocabulary(
  id BIGINT(6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  tuvung VARCHAR(255) NOT NULL,
  kanji VARCHAR(255) NOT NULL,
  phienam VARCHAR(255) NOT NULL,
  nghia VARCHAR(255) NOT NULL,
  vidu VARCHAR(255) NOT NULL
)

