CREATE TABLE login(
  id BIGINT(6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE login_role(
  login_id    BIGINT(6)    NOT NULL,
  role_id   BIGINT(6)    NOT NULL
);
CREATE TABLE role(
  id BIGINT(6) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);
